Update rpkg

diff --git a/rpkg b/rpkg
--- a/rpkg
+++ b/rpkg
@@ -9,6 +9,7 @@ FORCE_SORT=0                # Force sorting the repositories
 FORCE_PATCH=0               # Force searching for patches
 QUIET=0                     # Suppress the majority of print statements
 FORCE_IGNORE=0              # Ignore the checksum file and force a download
+VERBOSE=0                   # Print additional debugging information
 
 # Global Variables
 REPOS=()                    # Array of repositories (Auto-filled)
@@ -53,6 +54,8 @@ test_repo_speed() {
         | grep -oE "[^\"]*\.tar\.[^\" ]+" \
         | head -n 1)
 
+    [ "$VERBOSE" -eq 1 ] && { echo -e "$test_file"; }
+
     if [ -z "$test_file" ]; then
         echo "999"
         return
@@ -93,11 +96,15 @@ create_repolist() {
     content+="https://mirrors.ustc.edu.cn/lfs/lfs-packages/12.4/\n"
     content+="https://mirror.freedif.org/pub/lfs/lfs-packages/12.4/\n"
 
+    if [ "$VERBOSE" -eq 1 ]; then
+        echo -e "Creating generic $REPO_LIST"
+    fi
     echo -e "$content" > "$REPO_LIST"
 }
 
 load_repos() {
     local skip_sort=0
+    REPO_LEN=0
 
     while IFS= read -r line; do
         # if any comment in the REPO_LIST contains '# --lock' it will not sort.
@@ -129,7 +136,14 @@ load_repos() {
         echo -e "$prompt"
     fi
 
+    if [ "$VERBOSE" -eq 1 ]; then
+        for repo in ${REPOS[@]}; do
+            echo -e "  $repo"
+        done
+    fi
+
     # Sort repos by speed
+    local counter=1
     if [ "$REPO_LEN" -gt 1 ]; then
         if [ "$skip_sort" -eq 0 ] || [ "$FORCE_SORT" -eq 1 ]; then
             SORTING_IN_PROGRESS=1
@@ -150,10 +164,17 @@ load_repos() {
                         local speed_prompt="${TXT_BOLD_RED}${speed:0:5}s${TXT_END}"
                     fi
 
-                    echo -e "  $repo ... ${TXT_BOLD}[${speed_prompt}${TXT_BOLD}]${TXT_END}"
+                    if [ "$VERBOSE" -eq 1 ]; then
+                        local prompt="  $repo ... "
+                        prompt+="${TXT_BOLD}[${speed_prompt}${TXT_BOLD}]${TXT_END}"
+                        echo -e "$prompt"
+                    else
+                        echo -en "\e[K  $counter/$REPO_LEN: $repo ... ${TXT_BOLD}[$speed_prompt${TXT_BOLD}]\r"
+                    fi
                 fi
 
                 repo_speed_pairs+=("$repo|$speed")
+                ((counter++))
             done
 
             IFS=$'\n' repo_speed_pairs=($(sort -t'|' -k2 -n <<<"${repo_speed_pairs[*]}"))
@@ -172,7 +193,6 @@ load_repos() {
 
             write_sorted_repos
             SORTING_IN_PROGRESS=0
-            load_repos
 
         elif [ "$skip_sort" -eq 1 ]; then
             if [ "$QUIET" -eq 0 ]; then
@@ -201,14 +221,25 @@ write_sorted_repos() {
     for i in "${!REPOS[@]}"; do
         if [ "$i" -lt "$limit" ]; then
             echo "${REPOS[$i]}" >> "$temp_file"
+            if [ "$VERBOSE" -eq 1 ]; then
+                echo -e "${REPOS[$i]} - added to $temp_file"
+            fi
         else
             echo "# ${REPOS[$i]}" >> "$temp_file"
+            if [ "$VERBOSE" -eq 1 ]; then
+                echo -e "# ${REPOS[$i]} - added to $temp_file"
+            fi
         fi
     done
 
     # Overwrite original
     mv "$temp_file" "$REPO_LIST"
-    echo -e "${TXT_BOLD}Updated $REPO_LIST with sorted repositories...${TXT_END}"
+    if [ "$QUIET" -eq 0 ]; then
+        if [ "$VERBOSE" -eq 1 ]; then
+            echo -e "${TXT_YELLOW}$REPO_LIST overwritten with $temp_file${TXT_END}"
+        fi
+        echo -e "${TXT_BOLD}Updated $REPO_LIST with sorted repositories...${TXT_END}"
+    fi
 }
 
 pkg_search() {
@@ -221,8 +252,15 @@ pkg_search() {
     fi
     echo -e "$prefix${TXT_BOLD}Searching for $pkg...${TXT_END}"
 
+    if [ "$VERBOSE" -eq 1 ]; then
+        local args="-fL"
+    else
+        local args="-fsSL"
+    fi
+
+    local count=1
     for repo in "${REPOS[@]}"; do
-        path=$(curl -fsSL "$repo" \
+        path=$(curl $args "$repo" \
             --connect-timeout "$TIME_OUT" \
             -A "$USER_AGENT" --no-progress-bar \
             | grep -oE "$pkg[^\"]*\.tar\.[^\" ]+" \
@@ -230,9 +268,22 @@ pkg_search() {
 
         if [ -n "$path" ]; then
             SUCCESS_URLS+=("$repo$path")
-            echo -e "  $repo$path ... ${TXT_BOLD_GREEN}[FOUND]${TXT_END}"
+            if [ "$QUIET" -eq 1 ]; then
+                local prompt="\e[K  $path ${TXT_BOLD_GREEN}[FOUND]${TXT_END} in "
+                prompt+="${TXT_BOLD}${#SUCCESS_URLS[@]}/${#REPOS[@]}${TXT_END} repositories\r"
+                echo -en "$prompt"
+            else
+                echo -e "  $repo$path ... ${TXT_BOLD_GREEN}[FOUND]${TXT_END}"
+            fi
         else
-            echo -e "  $repo ... ${TXT_BOLD_RED}[NOT FOUND]${TXT_END}"
+            if [ "$QUIET" -eq 1 ]; then
+                local prompt="\e[K  $pkg ${TXT_BOLD_RED}[NOT FOUND]${TXT_END} in "
+                prompt+="${TXT_BOLD}$count${TXT_END} repositories\r"
+                echo -en "$prompt"
+            else
+                echo -e "  $repo ... ${TXT_BOLD_RED}[NOT FOUND]${TXT_END}"
+            fi
+            ((count++))
         fi
     done
 
@@ -245,7 +296,7 @@ pkg_search() {
 
         local err_prompt="${TXT_BOLD_RED}[Error]:${TXT_END} "
         err_prompt+="\"$pkg\" was not found in $REPO_LEN $repo_prompt..."
-        echo -e "$err_prompt" >&2
+        echo -e "\n$err_prompt" >&2
         return 1
     fi
 
@@ -279,8 +330,14 @@ patch_search() {
         echo -e "\n${TXT_BOLD}Searching for $name Patch...${TXT_END}"
     fi
 
+    if [ "$VERBOSE" -eq 1 ]; then
+        local args="-fL"
+    else
+        local args="-fsSL"
+    fi
+
     for repo in "${REPOS[@]}"; do
-        path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
+        path=$(curl $args "$repo" --connect-timeout "$TIME_OUT" \
             -A "$USER_AGENT" --no-progress-meter \
             | grep -oE "$name[^\"]*\.patch" \
             | head -n 1)
@@ -337,12 +394,14 @@ file_exists() {
         if [[ "$name" == *".patch" ]]; then
             file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1024}")
             local measurement="KB"
+            local file_type="Patch"
         else
             file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
             local measurement="MB"
+            local file_type="Package"
         fi
 
-        local prompt="\n${TXT_BOLD_YELLOW}Package [${TXT_YELLOW}$name${TXT_BOLD_YELLOW}] already exists in:${TXT_END} $PKG_DIR"
+        local prompt="\n${TXT_BOLD_YELLOW}$file_type [${TXT_YELLOW}$name${TXT_BOLD_YELLOW}] already exists in:${TXT_END} $PKG_DIR"
         prompt+="\n  ${TXT_BOLD}Size:${TXT_END} $file_size $measurement\n"
         prompt+="  ${TXT_BOLD}Location:${TXT_END} $full_file"
         echo -e "$prompt"
@@ -367,13 +426,17 @@ download_pkg() {
     for pkg_url in "${url_list[@]}"; do
         echo -e "\n${TXT_BOLD}Downloading:${TXT_END} $name\n  From: $pkg_url"
 
-        if [ "$QUIET" -eq 0 ]; then
-            local command_args="-fSL"
+        if [ "$VERBOSE" -eq 1 ]; then
+            local command_args="-fL"
         else
-            local command_args="-fsSL"
+            if [ "$QUIET" -eq 0 ]; then
+                local command_args="-fSL"
+            else
+                local command_args="-fsSL"
+            fi
         fi
 
-        if curl "$command_args" "$pkg_url" \
+        if curl $command_args "$pkg_url" \
             -A "$USER_AGENT" \
             -o "$PKG_DIR/$name" \
             --max-time "$MAX_TIMEOUT"; then
@@ -421,7 +484,12 @@ verify_checksum() {
     local actual_hash=$(md5sum "$PKG_DIR/$filename" | awk '{print $1}')
 
     if [[ "$expected_hash" == "$actual_hash" ]]; then
-        echo -e "  ${TXT_CYAN}Checksum verified!${TXT_END}"
+        local prompt="  ${TXT_CYAN}Checksum verified!${TXT_END}"
+        if [ "$VERBOSE" -eq 1 ]; then
+                    prompt+="  - Expected: $expected_hash\n"
+                    prompt+="  - Received: $actual_hash"
+        fi
+        echo -e "$prompt"
         return 0
     else
         local prompt="  ${TXT_RED}Checksum failed to verify: $filename${TXT_END}\n"
@@ -433,11 +501,17 @@ verify_checksum() {
 }
 
 download_sumlist() {
-    if [ "$QUIET" -eq 1 ]; then
+    if [ "$QUIET" -eq 0 ]; then
         echo -e "${TXT_BOLD}Download LFS checksum file...${TXT_END}"
     fi
 
-    curl -fsSL "$LFS_CHECKSUM" \
+    if [ "$VERBOSE" -eq 1 ]; then
+        local args="-fL"
+    else
+        local args="-fsSL"
+    fi
+
+    curl $args "$LFS_CHECKSUM" \
         -A "$USER_AGENT" \
         --connect-timeout "$TIME_OUT" \
         --max-time 10 \
@@ -603,15 +677,17 @@ main() {
         fi
     fi
 
-    while getopts ":hvfpqI-:" opt; do
+    while getopts ":hVvfpqI-:" opt; do
         case "$opt" in
             h)
                 help_info
                 exit 0
                 ;;
-            v)
+            V)
                 version_info
                 exit 0
+                ;;
+            v)  VERBOSE=1
                 ;;
             f)
                 FORCE_SORT=1
@@ -635,6 +711,9 @@ main() {
                     version)
                         version_info
                         exit 0
+                        ;;
+                    verbose)
+                        VERBOSE=1
                         ;;
                     force-sort)
                         FORCE_SORT=1
